# Generated by Django 3.2.13 on 2023-02-13 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testgosmak',
            name='Sapak_ady',
        ),
        migrations.RenameModel(
            old_name='Toporlar',
            new_name='Toparlar',
        ),
        migrations.CreateModel(
            name='Testmaglumatlary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testin_ady', models.CharField(max_length=255)),
                ('Sorag_sany', models.PositiveIntegerField()),
                ('Wagyt_limidi', models.PositiveIntegerField()),
                ('Sapagyn_ady', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sapaklar')),
                ('Topar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.toparlar')),
            ],
        ),
    ]
