# Generated by Django 3.2.13 on 2023-02-14 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230213_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmaglumatlary',
            name='Fakultedin_ady',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.fakultedlar'),
            preserve_default=False,
        ),
    ]
