# Generated by Django 3.2.13 on 2023-02-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testmaglumatlary_fakultedin_ady'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmaglumatlary',
            name='Fakultedin_ady',
        ),
        migrations.DeleteModel(
            name='Fakultedlar',
        ),
    ]
