# Generated by Django 3.2.13 on 2023-02-18 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230216_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testgosmak',
            name='Soragy',
        ),
        migrations.AddField(
            model_name='testgosmak',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.testmaglumatlary'),
            preserve_default=False,
        ),
    ]
