# Generated by Django 3.2.13 on 2023-02-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230218_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgosmak',
            name='Soragy',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
