# Generated by Django 3.2.13 on 2023-02-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_testgosmak_soragy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testgosmak',
            name='d',
        ),
    ]
