# Generated by Django 3.2.13 on 2023-03-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_testgosmak_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmaglumatlary',
            name='Sorag_sany',
        ),
    ]
