# Generated by Django 3.2.13 on 2023-03-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20230317_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sorag_sany',
            new_name='Sorag',
        ),
        migrations.RenameField(
            model_name='aktiw',
            old_name='Toparlar',
            new_name='Topar',
        ),
        migrations.RenameField(
            model_name='aktiw',
            old_name='Wagt',
            new_name='Wagt_limidi',
        ),
        migrations.RenameField(
            model_name='toparlar',
            old_name='Toparlar',
            new_name='Topar',
        ),
    ]
