# Generated by Django 3.2.13 on 2023-03-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20230317_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktiw',
            name='Wagt_limidi',
        ),
        migrations.AddField(
            model_name='aktiw',
            name='Wagyt_limidi',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aktiw',
            name='Sorag_sany',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Sorag',
        ),
        migrations.DeleteModel(
            name='Wagt',
        ),
    ]
