# Generated by Django 3.2.13 on 2023-03-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_testmaglumatlary_sorag_sany'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgosmak',
            name='dogry',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
