# Generated by Django 3.2.13 on 2023-04-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_testgosmak_dogry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmaglumatlary',
            name='Sorag_sany',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='testmaglumatlary',
            name='Wagyt_limidi',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='toparlar',
            name='Topar',
            field=models.SmallIntegerField(),
        ),
    ]
