# Generated by Django 3.2.13 on 2023-03-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Netijeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Talyp_belgi', models.PositiveIntegerField()),
                ('Dersin_ady', models.CharField(max_length=255)),
                ('Dogry_sany', models.PositiveIntegerField()),
                ('Yalnys_sany', models.PositiveIntegerField()),
            ],
        ),
    ]
