# Generated by Django 3.2.13 on 2023-03-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='netijeler',
            name='Dogry_goterim',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='netijeler',
            name='Yalnys_goterim',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
