# Generated by Django 3.2.13 on 2023-04-01 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_netijeler_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netijeler',
            name='Talyp_belgi',
        ),
    ]
