# Generated by Django 3.2.13 on 2023-04-03 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_netijeler_talyp_belgi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netijeler',
            name='Dersin_ady',
        ),
    ]
