# Generated by Django 3.2.13 on 2023-04-03 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_testgosmak_dogry'),
        ('student', '0005_remove_netijeler_dersin_ady'),
    ]

    operations = [
        migrations.AddField(
            model_name='netijeler',
            name='Dersin_ady',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.sapaklar'),
        ),
        migrations.AddField(
            model_name='netijeler',
            name='Topar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.toparlar'),
        ),
    ]
