# Generated by Django 3.2.13 on 2023-04-03 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20230403_1619'),
        ('student', '0007_auto_20230403_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='topar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.toparlar'),
        ),
    ]
