# Generated by Django 3.2.13 on 2023-04-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_topar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netijeler',
            name='Dogry_goterim',
        ),
        migrations.RemoveField(
            model_name='netijeler',
            name='Yalnys_goterim',
        ),
    ]
